# This file is automatically generated. Any changes will be lost. Edit the corresponding .in file instead. DO NOT COMMIT
#
# This code is Copyright (C) 2019 The Cambridge Crystallographic Data Centre
# (CCDC) of 12 Union Road, Cambridge CB2 1EZ, UK and a proprietary work of CCDC.
# This code may not be used, reproduced, translated, modified, disassembled or
# copied, except in accordance with a valid licence agreement with CCDC and may
# not be disclosed or redistributed in any form, either in whole or in part, to
# any third party. All copies of this code made in accordance with a valid
# licence agreement as referred to above must contain this copyright notice.
#
# No representations, warranties, or liabilities are expressed or implied in the
# supply of this code by CCDC, its servants or agents, except where such
# exclusion or limitation is prohibited, void or unenforceable under governing
# law.
#
'''
    ccdc_roche -  for internal CCDC and Roche API use, not exposed to the public.
'''
from __future__ import division, absolute_import, print_function

import ccdc

__version__ = '3.0.5'
__build__ = 'DEV'

# if ccdc.__version__ != __version__:
#     raise ImportError('Version mismatch between ccdc {} and ccdc_roche {} packages'.format(
#         ccdc.__version__, __version__))
